version: '3'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=hicoder'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - '3306'
    networks:
      - hicoder-network
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
    networks:
      - hicoder-network
  nginx:
    image: 'nginx:latest'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - hicoder-network
    depends_on:
      - spring-boot
  spring-boot:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - hicoder-network
    depends_on:
      - mysql
      - redis

networks:
  hicoder-network: