version: '3'
services:
  mysql-hicoder:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=hicoder'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
#    ports:
#      - '3306'
#      - '3306:3306'
    networks:
      - hicoder-network
    container_name: mysql-hicoder
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=verysecret --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100

  redis-hicoder:
    image: 'redis:latest'
#    ports:
#      - '6379'
#      - '6379:6379'
    networks:
      - hicoder-network
    container_name: redis-hicoder

  hicoder-backend:
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    container_name: hicoder-backend
    networks:
      - hicoder-network
    depends_on:
      - mysql-hicoder
      - redis-hicoder
    ports:
      - '8080:8080'

#  nginx:
#    image: 'nginx:latest'
##    restart: unless-stopped
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    networks:
#      - hicoder-network
#    depends_on:
#      - hicoder-backend

networks:
  hicoder-network: