version: '3'

services:
  postgres-hicoder:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=hicoder'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=verysecret'
    networks:
      - hicoder-network
    container_name: postgres-hicoder
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 2s
      retries: 100
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'


  redis-hicoder:
    image: 'redis:latest'
    networks:
      - hicoder-network
    container_name: redis-hicoder
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

#  hicoder-backend:
#    restart: always
#    build:
#        context: .
#        dockerfile: Dockerfile
#    container_name: hicoder-backend
#    networks:
#      - hicoder-network
#    depends_on:
#      - mysql-hicoder
#      - redis-hicoder
#
#
#  nginx:
#    image: 'nginx:latest'
#    container_name: nginx-hicoder
#    restart: unless-stopped
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    networks:
#      - hicoder-network
#    depends_on:
#      - hicoder-backend
#    ports:
#      - '80:80'
#      - '443:443'

volumes:
  postgres-data:
  redis-data:
networks:
  hicoder-network:
