version: '3'

services:
  mysql-hicoder:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=hicoder'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    networks:
      - hicoder-network
    container_name: mysql-hicoder
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=verysecret --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100
    volumes:
      - mysql-data:/var/lib/mysql


  redis-hicoder:
    image: 'redis:latest'
    networks:
      - hicoder-network
    container_name: redis-hicoder
    volumes:
      - redis-data:/data

#
#  hicoder-backend:
#    restart: always
#    build:
#        context: .
#        dockerfile: Dockerfile
#    container_name: hicoder-backend
#    networks:
#      - hicoder-network
#    depends_on:
#      - mysql-hicoder
#      - redis-hicoder
#
#
#  nginx:
#    image: 'nginx:latest'
#    container_name: nginx-hicoder
#    restart: unless-stopped
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    networks:
#      - hicoder-network
#    depends_on:
#      - hicoder-backend
#    ports:
#      - '80:80'
#      - '443:443'

volumes:
    mysql-data:
    redis-data:
networks:
  hicoder-network:

